// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20211128032535_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatAge")
                        .HasColumnType("int");

                    b.Property<string>("CatBreed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CatGender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CatAge = 2,
                            CatBreed = "Flame Point",
                            CatGender = "Male",
                            CatName = "Hobbes"
                        },
                        new
                        {
                            CatId = 2,
                            CatAge = 19,
                            CatBreed = "Tabby",
                            CatGender = "Male",
                            CatName = "Rikki"
                        },
                        new
                        {
                            CatId = 3,
                            CatAge = 5,
                            CatBreed = "Black Cat",
                            CatGender = "Female",
                            CatName = "Ash"
                        },
                        new
                        {
                            CatId = 4,
                            CatAge = 21,
                            CatBreed = "Gray",
                            CatGender = "Male",
                            CatName = "Rhode"
                        },
                        new
                        {
                            CatId = 5,
                            CatAge = 5,
                            CatBreed = "Tabby",
                            CatGender = "Male",
                            CatName = "Bobob"
                        },
                        new
                        {
                            CatId = 6,
                            CatAge = 9,
                            CatBreed = "Siamese",
                            CatGender = "Female",
                            CatName = "Loblob"
                        },
                        new
                        {
                            CatId = 7,
                            CatAge = 18,
                            CatBreed = "Orange",
                            CatGender = "Male",
                            CatName = "Mombob"
                        },
                        new
                        {
                            CatId = 8,
                            CatAge = 7,
                            CatBreed = "Russian Gray",
                            CatGender = "Male",
                            CatName = "Dobby"
                        },
                        new
                        {
                            CatId = 9,
                            CatAge = 16,
                            CatBreed = "Persian",
                            CatGender = "Male",
                            CatName = "Calvin"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DogAge")
                        .HasColumnType("int");

                    b.Property<string>("DogBreed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DogGender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            DogAge = 15,
                            DogBreed = "Jack Russel",
                            DogGender = "Female",
                            DogName = "Clio"
                        },
                        new
                        {
                            DogId = 2,
                            DogAge = 19,
                            DogBreed = "Shetland Sheepdog",
                            DogGender = "Male",
                            DogName = "Sparky"
                        },
                        new
                        {
                            DogId = 3,
                            DogAge = 11,
                            DogBreed = "Black Lab",
                            DogGender = "Male",
                            DogName = "Alphonse"
                        },
                        new
                        {
                            DogId = 4,
                            DogAge = 11,
                            DogBreed = "Golden Doodle",
                            DogGender = "Male",
                            DogName = "Bob"
                        },
                        new
                        {
                            DogId = 5,
                            DogAge = 2,
                            DogBreed = "Golden Retriever",
                            DogGender = "Female",
                            DogName = "Rob"
                        },
                        new
                        {
                            DogId = 6,
                            DogAge = 1,
                            DogBreed = "Pomeranian",
                            DogGender = "Male",
                            DogName = "Dob"
                        },
                        new
                        {
                            DogId = 7,
                            DogAge = 5,
                            DogBreed = "Cocker Spaniel",
                            DogGender = "Female",
                            DogName = "Mob"
                        },
                        new
                        {
                            DogId = 8,
                            DogAge = 7,
                            DogBreed = "Brittany",
                            DogGender = "Female",
                            DogName = "Lob"
                        },
                        new
                        {
                            DogId = 9,
                            DogAge = 19,
                            DogBreed = "Australian",
                            DogGender = "Female",
                            DogName = "Cloe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
